<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Home' => 'หน้าแรก',
  'The button type "{type}" is not supported.' => 'ไม่รองรับประเภทปุ่มนี้',
  'Are you sure you want to delete this item?' => 'ยืนยันการลบอีกครั้ง',
  'Delete' => 'ลบ',
  'Displaying {start}-{end} of {count} result(s).' => 'แสดง {start}-{end} จากทั้งหมด {count}.',
  'Either "name" or "value" must be specified for CDataColumn.' => 'อย่างน้อยต้องมี "name" หรือ "value" ต้องถูกกำหนดใน CDataColumn',
  'No results found.' => 'ไม่พบผลลัพธ์',
  'Not set' => 'ไม่ได้ตั้งค่า',
  'Please specify the "attributes" property.' => 'กรุณากำหนด "attributes"',
  'Please specify the "data" property.' => 'กรุณากำหนด "data"',
  'Sort by: ' => 'เรียงโดย:  ',
  'The "dataProvider" property cannot be empty.' => 'Властивість "dataProvider" не може бути порожньою.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Атрибут повинен бути заданий у форматі "Ім\'я:Тип:Заголовок". "Тип" та "Заголовок" не обов\'язкові.',
  'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Стовпець повинен бути заданий у форматі "Name:Type:Label". "Тип" та "Заголовок" не обов\'язкові.',
  'The property "itemView" cannot be empty.' => 'Властивість "itemView" не може бути порожньою.',
  'Total {count} result(s).' => 'ทั้งหมด {count}',
  'Update' => 'อัพเดท',
  'View' => 'View',
  '{class} must specify "model" and "attribute" or "name" property values.' => 'У класі {class} повинні бути задані значення властивостей "model" та "attribute", або значення "name".',
);
